name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: ./agent/java-diagnostic-plugin
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Find the generated ZIP file
        id: find_zip
        run: |
          ZIP_FILE=$(realpath build/distributions/*.zip)
          echo "ZIP_PATH=$ZIP_FILE" >> $GITHUB_ENV

      - name: Verify ZIP file existence
        run: |
          if [ ! -f "${{ env.ZIP_PATH }}" ]; then
            echo "Error: ZIP file not found at ${{ env.ZIP_PATH }}"
            exit 1
          fi
          echo "ZIP file located at: ${{ env.ZIP_PATH }}"

      - name: Upload assert
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ZIP_PATH }}
          asset_name: java-diagnostic-plugin.zip
          asset_content_type: application/zip

